name: serviceC deploy workflow
on:
  push:
    tags:
      - 'develop-serviceC-v*'
      - 'release-serviceC-v*'

env:
  SERVICE_NAME: app
  BRANCH: ${GITHUB_REF##*/}
  IMAGE_TAG: ${GITHUB_REF##*/}_${GITHUB_SHA::6}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo ${{ env.BRANCH }}
          echo ${{ github.ref }}
          echo "run serviceC test"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: |
          echo "run serviceC build"

  develop-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/develop')
    steps:
      - name: Run Build
        run: |
          echo "run serviceC develop deploy"  

  release-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release')
    steps:
      - name: Run Build
        run: |
          echo "run serviceC release deploy"