name: serviceA test workflow
on:
  push:
    paths:
      - 'serviceA/**'
      - '.github/workflows/serviceA.yml'
    branches:
      - 'develop'
      - 'release'
    tags-ignore:
      - 'develop-**'
      - 'release-**'
  pull_request:
    paths:
      - 'serviceA/**'
      - '.github/workflows/serviceA.yml'
    branches-ignore:
      - "release"

env:
  SERVICE_NAME: app
  BRANCH: ${GITHUB_REF##*/}
  IMAGE_TAG: ${GITHUB_REF##*/}_${GITHUB_SHA::6}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo "run serviceA test"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: |
          echo "run serviceA build"