name: TEST1 workflow
on:
  push:
    paths:
      - 'test1/**'
      - '.github/workflows/test1.yml'
    branches:
      - 'develop'
      - 'release'
    tags-ignore:
      - 'develop-**'
      - 'release-**'
  pull_request:
    paths:
      - 'test1/**'
      - '.github/workflows/test1.yml'

env:
  SERVICE_NAME: app
  BRANCH: ${GITHUB_REF##*/}
  IMAGE_TAG: ${GITHUB_REF##*/}_${GITHUB_SHA::6}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo "run test1 test"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: |
          echo "run test1 build"