name: TEST2 workflow
on:
  push:
    paths:
      - 'test2/**'
      - '.github/workflows/test2.yml'
    branches:
      - 'develop'
      - 'release'
    tags-ignore:
      - 'develop-test2-v*'
      - 'release-test2-v*'
  pull_request:
    paths:
      - 'test2/**'
      - '.github/workflows/test2.yml'

env:
  SERVICE_NAME: app
  BRANCH: ${GITHUB_REF##*/}
  IMAGE_TAG: ${GITHUB_REF##*/}_${GITHUB_SHA::6}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo "run test2 test"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: |
          echo "run test2 build"